Multidimensional array broadcasting implementation is added as four cuda kernels, src/cuda13 M-Array,N-Array->M-Array (M(x,y,z,w,t...), N(1,1,1,w,1...)) src/cuda14 Array,Array->Array (M(w,t), N(w)) (matrix, column vector) src/cuda16  Array,Array->Array (Multi dimensional broadcast) src/cuda17  Array,Array->Array (Multi dimensional broadcast)
cuda13 and cuda14 takes advantage of data reuse with shared memory, works with vectors
cuda16 is generelised broadcast operation kernel which supports all dimensions without shared memory
cuda17 is same with cuda16, however for loops are unrolled and inputs are parametirised to avoid
moving arrays to GPU and using them from shared memory
currently calling cuda17 kernel is not working,
error:
ERROR: UndefVarError: stride_x not defined
 in .+(::Knet.KnetArray{Float64,3}, ::Knet.KnetArray{Float64,3}) at /.julia/v0.5/Knet/src/broadcast.jl:166